### ISSUE TITLE
Unable to read from socket - Face DOWN | read: message too long

### ISSUE THREAD

**Issue by yoursunny** [named-data/ndnd#112]
It appears that a **udp6** face defined in `.dv.neighbors` is created with incorrect MTU, such that the forwarder attempts to send overly long packets.

## Topology

There are two IPv6 only servers located in VNO and EWR.
They are connected over the public Internet with MTU=1420 links.

**ndnd.yml** in VNO is written as follows:

```yaml
dv:
  advertise_interval: 5000
  keychain: insecure
  neighbors:
    - uri: udp6://[2a0a:6040:a313:a100:c9be::9d63]:6363
  network: /yoursunny
  router: /yoursunny/dv/vno
  router_dead_interval: 30000
  trust_anchors: []
fw:
  core:
    log_file: ""
    log_level: INFO
  faces:
    congestion_marking: true
    lock_threads_to_cores: false
    queue_size: 1024
    tcp:
      enabled: false
      lifetime: 600
      port_unicast: 6363
      reconnect_interval: 10
    udp:
      enabled_multicast: false
      enabled_unicast: true
      lifetime: 600
      multicast_address_ipv4: 224.0.23.170
      multicast_address_ipv6: ff02::114
      port_multicast: 56363
      port_unicast: 6363
    unix:
      enabled: true
      socket_path: /run/nfd/nfd.sock
    websocket:
      bind: ""
      enabled: true
      port: 9696
      tls_cert: ""
      tls_enabled: false
      tls_key: ""
  fw:
    lock_threads_to_cores: false
    queue_size: 1024
    threads: 2
  mgmt:
    allow_localhop: false
  tables:
    content_store:
      admit: true
      capacity: 1024
      replacement_policy: lru
      serve: true
    dead_nonce_list:
      lifetime: 6000
    fib:
      algorithm: nametree
      hashtable:
        m: 3
    network_region:
      regions:
        - /yoursunny
    rib:
      readvertise_nlsr: true
```

## Commands

**ndnd daemon** is running in a Docker container with explicitly specified IPv6 addresses that match **ndnd.yml** of the neighbor.

VNO serves a file with size 1 GiB:

```bash
dd if=/dev/urandom of=1.bin bs=1024 count=1048576 status=progress
docker run -i --rm --cap-drop ALL --network none --user $(id -u):$(id -g) -v run-ndn:/run/nfd docker.yoursunny.dev/ndnd put -expose /yoursunny/vno/1.bin <1.bin
```

EWR attempts to retrieve the file:

```bash
docker run -it --rm --cap-drop ALL --network none --user $(id -u):$(id -g) -v run-ndn:/run/nfd docker.yoursunny.dev/ndnd cat /yoursunny/vno/1.bin >1.bin
```

## Expected Result

EWR receives a file that has the same size and digest as the sending host.

## Actual Result

EWR receives file content:

```text
time=2025-01-26T03:51:59.184Z level=ERROR msg="Error fetching object" tag=cat err="consume: fetch seg failed with result: Timeout"
```

VNO ndnd prints the following errors in its logs:

```text
time=2025-01-26T03:51:43.309Z level=WARN msg="Unable to read from socket - Face DOWN" tag="unicast-udp-transport (face=4 remote=udp6://[2a0a:6040:a313:a100:c9be::9d63]:6363 local=udp6://[2a13:9401:0:1::57e1:9d63]:6363)" err="read udp6 [2a13:9401:0:1::57e1:9d63]:6363->[2a0a:6040:a313:a100:c9be::9d63]:6363: read: message too long"
time=2025-01-26T03:51:43.310Z level=INFO msg="Unregistered face" tag=face-table faceid=4
time=2025-01-26T03:51:46.029Z level=INFO msg="Accepting new UDP face" tag="udp-listener (udp6://[::]:6363)" uri=udp6://[2a0a:6040:a313:a100:c9be::9d63]:6363
time=2025-01-26T03:51:47.318Z level=WARN msg="Unable to read from socket - Face DOWN" tag="unicast-udp-transport (face=7 remote=udp6://[2a0a:6040:a313:a100:c9be::9d63]:6363 local=udp6://[::]:6363)" err="read udp6 [2a13:9401:0:1::57e1:9d63]:6363->[2a0a:6040:a313:a100:c9be::9d63]:6363: read: message too long"
time=2025-01-26T03:51:47.319Z level=INFO msg="Unregistered face" tag=face-table faceid=7
```

**strace** reveals that it's attempting to write a message longer than the MTU, which is forbidden in IPv6:

```text
[pid 11309] read(11,  <unfinished ...>
[pid 11309] <... read resumed>"d8b\6\0\0k\325\222 P.\5,\7$\10\tyoursunny\10\3vno"..., 281600) = 58
[pid 11309] read(11,  <unfinished ...>
[pid 11309] <... read resumed>0xc000446000, 281600) = -1 EAGAIN (Resource temporarily unavailable)
[pid 11309] write(11, "d\375\37\262b\6\0\0k\325\222 P\375\37\246\6\375\37\242\7$\10\tyoursunn"..., 8118 <unfinished ...>
[pid 11309] <... write resumed>)        = 8118
[pid 11309] read(11,  <unfinished ...>
[pid 11309] <... read resumed>0xc000446000, 281600) = -1 EMSGSIZE (Message too long)
```

## Potential Solutions

The `.dv.neighbors` field should accept the link MTU.
The daemon should perform NDNLPv2 fragmentation and never send packets longer than the MTU.

**Comment by pulsejet** [comment]
MTU is now configurable in DV neighbors config

```yaml
dv:
  ...
  neighbors:
    - uri: udp4://localhost:6364
      mtu: 1420
```

You can also set the default UDP mtu for the forwarder.

When MTU is less than max NDN packet size, NDNLP fragmentation is automatically used. Please note that fragmentation is not well tested or optimized, but it seems to be working.
