### ISSUE TITLE
[dv] no valid signer found

### ISSUE THREAD

**Issue by yoursunny** [named-data/ndnd#115]
Following the the example given in [daemon-example.md](https://github.com/named-data/ndnd/blob/37479596ae397db6218c4d8103772a0f374e3b93/docs/daemon-example.md?plain=1#L130-L132), I made a two node network between VNO and EWR.

## Configure File

VNO is configured as below.
EWR configuration is similar.

```yaml
dv:
  advertise_interval: 5000
  keychain: dir:///keychain
  neighbors:
    - mtu: 1372
      uri: udp6://[2a0a:6040:a313:a100:c9be::9d63]:6363
  network: /yoursunny/dv
  router: /yoursunny/dv/vno
  router_dead_interval: 30000
  trust_anchors:
    - /yoursunny/dv/KEY/%E1%EC%88%B3%15%E8bN/NA/v=1737900774950
fw:
  core:
    log_file: ""
    log_level: INFO
  faces:
    congestion_marking: true
    lock_threads_to_cores: false
    queue_size: 1024
    tcp:
      enabled: false
      lifetime: 600
      port_unicast: 6363
      reconnect_interval: 10
    udp:
      default_mtu: 1200
      enabled_multicast: false
      enabled_unicast: true
      lifetime: 600
      multicast_address_ipv4: 224.0.23.170
      multicast_address_ipv6: ff02::114
      port_multicast: 56363
      port_unicast: 6363
    unix:
      enabled: true
      socket_path: /run/nfd/nfd.sock
    websocket:
      bind: ""
      enabled: true
      port: 9696
      tls_cert: ""
      tls_enabled: false
      tls_key: ""
  fw:
    lock_threads_to_cores: false
    queue_size: 1024
    threads: 2
  mgmt:
    allow_localhop: false
  tables:
    content_store:
      admit: true
      capacity: 1024
      replacement_policy: lru
      serve: true
    dead_nonce_list:
      lifetime: 6000
    fib:
      algorithm: nametree
      hashtable:
        m: 3
    network_region:
      regions:
        - /yoursunny
    rib:
      readvertise_nlsr: true
```

## Keychain Content

VNO's keychain contains these files: [vno-keychain.tar.gz](https://github.com/user-attachments/files/18550388/vno-keychain.tar.gz)
It has the root certificate, self certificate signed by root, and self key.
Headers are listed below:

```text
-----BEGIN NDN CERT-----
Name: /yoursunny/dv/KEY/%E1%EC%88%B3%15%E8bN/NA/v=1737900774950
SigType: Ed25519
SignerKey: /yoursunny/dv/KEY/%E1%EC%88%B3%15%E8bN
Validity: 2025-01-26 14:12:54 +0000 UTC - 2026-01-26 14:12:54 +0000 UTC
-----END NDN CERT-----

-----BEGIN NDN CERT-----
Name: /yoursunny/dv/vno/32=DV/KEY/%D8%096%2B%96%3D%3D%24/NA/v=1737900775916
SigType: Ed25519
SignerKey: /yoursunny/dv/KEY/%E1%EC%88%B3%15%E8bN
Validity: 2025-01-26 14:12:55 +0000 UTC - 2026-01-26 14:12:55 +0000 UTC
-----END NDN CERT-----

-----BEGIN NDN KEY-----
Name: /yoursunny/dv/vno/32=DV/KEY/%D8%096%2B%96%3D%3D%24
SigType: Ed25519
-----END NDN KEY-----
```

## Expected Behavior

The routing session establishes.

## Actual Behavior

VNO's ndnd container log has these error messages:

```text
time=2025-01-26T14:19:30.712Z level=ERROR msg="Failed to produce op" tag=dv-prefix err="no valid signer found for /yoursunny/dv/vno/32=DV/32=PFX/t=1737901170/seq=1"
time=2025-01-26T14:19:30.716Z level=ERROR msg="SvSync failed to find valid signer" tag="svs (/yoursunny/dv/32=DV/32=PFS)" name="/yoursunny/dv/32=DV/32=PFS/v=3"
time=2025-01-26T14:19:30.717Z level=ERROR msg="Failed to produce advertisement" tag=dv-advert err="no valid signer found for /localhop/yoursunny/dv/vno/32=DV/32=ADV/t=1737901170"
time=2025-01-26T14:19:35.716Z level=ERROR msg="Failed to send active sync interest" tag=dv-advert err="no signer found for /localhop/yoursunny/dv/32=DV/32=ADS/32=ACT/v=3"
time=2025-01-26T14:19:35.717Z level=ERROR msg="Failed to send passive sync interest" tag=dv-advert err="no signer found for /localhop/yoursunny/dv/32=DV/32=ADS/32=PSV/v=3"
```

Full log file: [ndnd.log](https://github.com/user-attachments/files/18550380/ndnd.log)
